### PR TITLE
change: vc leave handling

### PR DESCRIPTION
**Pull request by RadNotRed**
This makes it so someone who isn't in the vc, can't make the bot leave (this ultimately fixes the issue below) when trying to make the bot leave while not being in vc
```
2023-9-16 23:44:35 ERROR: TypeError: Cannot read properties of null (reading 'name')
2023-9-16 23:44:36 ERROR: There was an error while executing this command!
```

When the bot is alone in vc for 10 seconds, it automatically leaves the channel

### CODE REVIEW

**Comment by RadNotRed** [comment]
(sorry if i fucked up the formatting, it should follow the formatting rules still though)

**Comment by FaiThiX** [comment]
When the bot is alone in vc for 10 seconds, it automatically leaves the channel is great, but you just could add a check if the user who tries to disconnect the bot is in the same channel. Look at this for an example: [Commit in my fork](https://github.com/FaiThiX/rustplusplus/commit/7f2e1bfa99165ad6a85e34ae54c3fd22bd7d7a4b)

**Comment by RadNotRed** [comment]
> When the bot is alone in vc for 10 seconds, it automatically leaves the channel is great, but you just could add a check if the user who tries to disconnect the bot is in the same channel. Look at this for an example: [Commit in my fork](https://github.com/FaiThiX/rustplusplus/commit/7f2e1bfa99165ad6a85e34ae54c3fd22bd7d7a4b)

Only the people in the same vc can disconnect the bot currently, is that what you meant?

**Comment by FaiThiX** [comment]
> > When the bot is alone in vc for 10 seconds, it automatically leaves the channel is great, but you just could add a check if the user who tries to disconnect the bot is in the same channel. Look at this for an example: [Commit in my fork](https://github.com/FaiThiX/rustplusplus/commit/7f2e1bfa99165ad6a85e34ae54c3fd22bd7d7a4b)
> 
> Only the people in the same vc can disconnect the bot currently, is that what you meant?

yes exactly

**Comment by RadNotRed** [comment]
> > > When the bot is alone in vc for 10 seconds, it automatically leaves the channel is great, but you just could add a check if the user who tries to disconnect the bot is in the same channel. Look at this for an example: [Commit in my fork](https://github.com/FaiThiX/rustplusplus/commit/7f2e1bfa99165ad6a85e34ae54c3fd22bd7d7a4b)
> > 
> > 
> > Only the people in the same vc can disconnect the bot currently, is that what you meant?
> 
> yes exactly

thats already in the bot

**Comment by RadNotRed** [comment]
Oh no it isnt

**Comment by alexemanuelol** [comment]
Could you remove formatting changes that you've done as well as remove the changes to package-lock.json

**Comment by RadNotRed** [comment]
> Could you remove formatting changes that you've done as well as remove the changes to package-lock.json

it should™️ be fine now

**Comment by alexemanuelol** [comment]
Still alot of formatting changes, remove changes from package.json and package-lock.json.
I dont like that you have to be in vc to make the bot leave, remove that part.

**Comment by RadNotRed** [comment]
> Still alot of formatting changes, remove changes from package.json and package-lock.json. I dont like that you have to be in vc to make the bot leave, remove that part.

So you just want it to dc after 10 seconds?

**Comment by alexemanuelol** [comment]
Progress?

**Comment by alexemanuelol** [comment]
Added in: 08f2033fcd042558fa76cd768de88f6240eee492

**Pull request closed without merging**
