### PR TITLE
Fix Voice Integration not working for Linux Platform

### PR DESCRIPTION
**Pull request by FaiThiX**
This commit fixes the Problem that the bot can connect to a voice channel but will never say anything. Also, it fixes a bug where the bot sends an error to the console if the user who tries to disconnect the bot with `/voice leave` is not in a voice channel. With this PR this will no longer be possible. The bot is only disconnectable if the user is in the same channel as the bot is. 

Things to do after update:

- Remove package-lock.json
- Remove the node_modules folder
- **Only on Linux:** Install ffmpeg using the apt package manager `sudo apt install ffmpeg` 
- run `npm install`

### CODE REVIEW

**Comment by alexemanuelol** [comment]
Feels like ffmpeg package is quite old and less used then the ffmpeg-static package.

regarding the change to only allow disconnect if you're in the same vc, I dont want that part.

**Comment by FaiThiX** [comment]
> Feels like ffmpeg package is quite old and less used then the ffmpeg-static package.
> 
> regarding the change to only allow disconnect if you're in the same vc, I dont want that part.

Quiet old maybe but its the one that is working on linux and windows machines, not like ffmpeg static only works on windows machines

**Comment by alexemanuelol** [comment]
This doesn't work for me on windows 10.

**Comment by FaiThiX** [comment]
for me on windows 10/11 and ubuntu 22.04 and debian 12 it works perfectly fine. but ffmpeg-static wont work on linux machines. but if you dont want to switch it over than we can leave it like it is. maybe we remove the voice feature entirely until there is a fix for the problem available

**Comment by alexemanuelol** [comment]
Removing it completely won't solve anything. Works fine for me as it is right now on Windows.

**Comment by alexemanuelol** [comment]
image

**Pull request closed without merging**
